version: '3'
services:
  bot:
    container_name: chizik_bot
    depends_on:
    - db
    restart: unless-stopped
    command: sh -c "
        apk add gcc musl-dev libffi-dev openssl-dev
        && pip3 install -r requirements.txt
        && uvicorn main:app --host 0.0.0.0 --port ${API_PORT}"
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    ports:
      - "${API_PORT}:8080"
    image: python:alpine
    volumes:
    - /mnt/w/Python/chizik:/srv
    working_dir: /srv

  db:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./container/db/conf.d:/etc/mysql/conf.d
      - ./container/db/data:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
