version: '3'
services:
  bot:
    container_name: chizik_bot
    depends_on:
    - db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    command: sh -c "
        apk add gcc musl-dev libffi-dev openssl-dev
        && pip3 install -r requirements.txt
        && python3 -u main.py"
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - chizik
    image: python:alpine
    volumes:
    - /mnt/w/Python/chizik:/srv
    working_dir: /srv

  db:
    container_name: chizik_db
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./container/db/conf.d:/etc/mysql/conf.d
      - ./container/db/data:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - chizik
    restart: always

  web:
    container_name: chizik_web
    image: nodejs:lts-alpine
    ports:
      - 11030:3000
    volumes:
    - /mnt/w/Python/chizik:/srv
    working_dir: /srv/web
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - chizik
    restart: always
    command: sh -c "
      cd /srv/web
      && rm -rf .next
      && yarn install
      && yarn build
      && yarn start"

networks:
  chizik:
    driver: bridge
