version: '3'
services:
  bot:
    container_name: chizik_bot
    depends_on:
    - db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    command: sh -c "
        apk add gcc musl-dev libffi-dev openssl-dev
        && pip3 install -r requirements.txt
        && python3 -u main.py"
    env_file: .env
    environment:
      FAST_API_PORT: FAST_API_PORT
      TZ: Asia/Seoul
    networks:
      - backend
    image: python:alpine
    volumes:
    - /mnt/w/Python/chizik:/srv
    working_dir: /srv

  db:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./container/db/conf.d:/etc/mysql/conf.d
      - ./container/db/data:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
